#!/usr/bin/env python

import argparse, pycbc
import pycbc.workflow as wf
from ligo.segments import segment

parser = argparse.ArgumentParser()
parser.add_argument("--output-dir", default=None,
                    help="Path to output directory.")

wf.add_workflow_command_line_group(parser)
opts = parser.parse_args()

pycbc.init_logging(True)
workflow = wf.Workflow(opts, "match_tf2e")
wf.makedir(opts.output_dir)

exe = wf.Executable(workflow.cp, "match", ifos=['TF2E'],
                              out_dir=opts.output_dir)
upper= 132192
lower = 1
while lower <= upper:
    node = exe.create_node()
    node.add_opt("--lower-limit", lower)
    node.add_opt("--upper-limit", lower + 543)
    node.set_memory(10000)
    file = node.new_output_file_opt(segment([lower, lower+543]), ".txt",
                                    "--output-file")
    workflow += node
    lower += 544
workflow.save('tf2e_match.dax')
